config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations"}

  match 'users/:id' => 'deleteuser#destroy', :via => :delete, :as => :admin_destroy_user

  match 'statistics' => 'statistics#index', :via => :get
  match 'statistics' => 'statistics#create', :via => :post
  match 'statistics/:id' => 'statistics#destroy', :via => :delete

  match 'personal_statistics' => 'personal_statistics#index', :via => :get
  match 'personal_statistics' => 'personal_statistics#create', :via => :post
  match 'personal_statistics/:id' => 'personal_statistics#destroy', :via => :delete

  get 'contatti/contatti'

end

app/views/layouts/_airports.html.erb
<optgroup label="Italia">
  <option id="6537821" value="aho" label="Alghero">Alghero</option>
  <option id="6542126" value="aoi" label="Ancona">Ancona</option>
  <option id="6542001" value="bri" label="Bari">Bari</option>
  <option id="6541998" value="blq" label="Bologna">Bologna</option>
  <option id="6540125" value="cag" label="Cagliari">Cagliari</option>
  <option id="6541468" value="cta" label="Catania">Catania</option>
  <option id="3176219" value="goa" label="Genova">Genova</option>
  <option id="3176959" value="flr" label="Firenze">Firenze Peretola</option>
  <option id="6534232" value="suf" label="Lamezia Terme">Lamezia Terme</option>
  <option id="3173435" value="mila" label="Milano">Milano (Qualsiasi)</option>
  <option id="3173435" value="bgy" label="Milano">Milano Bergamo Orio al Serio</option>
  <option id="3173435" value="lin" label="Milano">Milano Linate (LIN)</option>
  <option id="3173435" value="mxp" label="Milano">Milano Malpensa (MXP)</option>
  <option id="3172394" value="nap" label="Napoli">Napoli</option>
  <option id="3172087" value="olb" label="Olbia">Olbia</option>
  <option id="6542127" value="pmo" label="Palermo">Palermo</option>
  <option id="3171457" value="pmf" label="Parma">Parma</option>
  <option id="3171180" value="peg" label="Perugia">Perugia</option>
  <option id="3171168" value="psr" label="Pescara">Pescara</option>
  <option id="3170647" value="psa" label="Pisa">Pisa</option>
  <option id="2523630" value="reg" label="Reggio Calabria">Reggio Calabria</option>
  <option id="3169361" value="rmi" label="Rimini">Rimini</option>
  <option id="3169070" value="rome" label="Roma">Roma (Qualsiasi)</option>
  <option id="3169070" value="cia" label="Roma">Roma Ciampino (CIA)</option>
  <option id="3169070" value="fco" label="Roma">Roma Fiumicino (FCO)</option>
  <option id="3165525" value="trn" label="Torino">Torino</option>
  <option id="3165186" value="trs" label="Trieste">Trieste</option>
  <option id="3164603" value="veni" label="Venezia">Venezia (Qualsiasi)</option>
  <option id="3164603" value="vce" label="Venezia">Venezia Marco Polo</option>
  <option id="3164603" value="tsf" label="Venezia">Venezia Treviso Sant'Angelo</option>
  <option id="3164527" value="vrn" label="Verona">Verona</option>
</optgroup>
<!-- Europa -->
<optgroup label="Europa">
  <option id="264371" value="ath" label="Atene">Atene</option>
  <option id="2759794" value="ams" label="Amsterdam">Amsterdam</option>
  <option id="6356055" value="bcn" label="Barcellona">Barcellona</option>
  <option id="2950159" value="berl" label="Berlino">Berlino (Qualsiasi)</option>
  <option id="2950159" value="sxf" label="Berlino">Berlino Schoenefield</option>
  <option id="2950159" value="txl" label="Berlino">Berlino Tegel</option>
  <option id="2618424" value="cope" label="Copenaghen">Copenaghen</option>
  <option id="2964574" value="dub" label="Dublino">Dublino</option>
  <option id="7285902" value="gva" label="Ginevra">Ginevra</option>
  <option id="658226" value="hel" label="Helsinki">Helsinki</option>
  <option id="745044" value="ista" label="Instabul">Instabul (Qualsiasi)</option>
  <option id="2267057" value="lis" label="Lisbona">Lisbona</option>
  <option id="2643743" value="lond" label="Londra">Londra (Qualsiasi)</option>
  <option id="2643743" value="lcy" label="Londra">Londra City</option>
  <option id="2643743" value="lgw" label="Londra">Londra Gatwick</option>
  <option id="2643743" value="lhr" label="Londra">Londra Heatrow</option>
  <option id="2643743" value="ltn" label="Londra">Londra Luton</option>
  <option id="2643743" value="sen" label="Londra">Londra Southend</option>
  <option id="2643743" value="stn" label="Londra">Londra Stansted</option>
  <option id="3117735" value="mad" label="Madrid">Madrid</option>
  <option id="2993458" value="muc" label="Monaco di Baviera">Monaco di Baviera</option>
  <option id="524901" value="mosc" label="Mosca">Mosca (Qualsiasi)</option>
  <option id="6453366" value="oslo" label="Oslo">Oslo (Qualsiasi)</option>
  <option id="6455259" value="pari" label="Parigi">Parigi (Qualsiasi)</option>
  <option id="6455259" value="bva" label="Parigi">Parigi Beauvais</option>
  <option id="6455259" value="cdg" label="Parigi">Parigi Charles De Gaulle</option>
  <option id="6455259" value="ory" label="Parigi">Parigi Orly</option>
  <option id="3067696" value="prg" label="Praga">Praga</option>
  <option id="2673730" value="stoc" label="Stoccolma">Stoccolma (Qualsiasi)</option>
  <option id="6695624" value="wars" label="Varsavia">Varsavia (Qualsiasi)</option>
  <option id="2761369" value="vie" label="Vienna">Vienna</option>
</optgroup>

app/views/layouts/_alerts.html.erb
<p class="notice devise_format"><%= notice %></p>
<p class="alert devise_format"><%= alert %></p>

app/views/layouts/_cars.html.erb
    <div class="padding-div">

        <div style="float: left; width: 30%; padding-right: 20px;">
            <label>Città ritiro:</label>
            <select id="cittaRitiro">
                <option value="none" disabled selected>Seleziona la città di ritiro</option>
                <%= render 'layouts/cities' %>
            </select>
        </div>

        <div style="float: left; width: 30%; padding-right: 20px;">
            <label>Città consegna:</label>
            <select id="cittaConsegna">
                <option value="none" disabled selected>Seleziona la città di consegna (default: città ritiro)</option>
                <%= render 'layouts/cities' %>
            </select>
        </div>

        <div style="clear:both; height: 70px;"></div>

        <div style="float: left; width: 15%; padding-right: 20px;">
            <label>Ritiro:</label>
            <input type="text" id="dataRitiro" class="datepicker"><br/><br/>
        </div>

        <div style="float: left; width: 10%; padding-right: 50px;">
            <label>Orario: </label>
            <input type="time" id="oraRitiro" value="10:00" step="1800"><br/><br/>
        </div>

        <div style="float: left; width: 15%; padding-right: 20px;">
            <label>Consegna: </label>
            <input type="text" id="dataConsegna" class="datepicker"><br/><br/>
        </div>

        <div style="float: left; width: 10%; padding-right: 20px;">
            <label>Orario: </label>
            <input type="time" id="oraConsegna" value="10:00" step="1800"><br/><br/>
        </div>

        <div style="clear:both; height: 70px;"></div>

        <div style="float: left; width: 15%; padding-right: 50px;">
            <label>Passeggeri:</label>
            <select id="numeroPasseggeri">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7+">7+</option>
            </select>
        </div>

        <div style="float: left; width: 15%; padding-right: 50px;">
            <label>Età conducente: <h6>(deve essere compresa tra 21 e 99)</h6></label>
            <input value="30" id="etaConducente" type="text">
        </div>

        <div style="clear:both;"></div>
        
    </div>

    <div style="clear:both;"></div>
    <br/>

app/views/layouts/_center.html.erb
<% if current_user %>
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#tab_voli" OnClick="set_voli_id(); return false;">Voli</a></li>
                <li class="tab col s3"><a href="#tab_hotel" OnClick="set_hotel_id(); return false;">Hotel</a></li>
                <% if current_user.has_role? :company_user or current_user.has_role? :admin %>
                <li class="tab col s3"><a href="#tab_auto" OnClick="set_auto_id(); return false;">Auto</a></li>
                <% end %>
            </ul>
        </div>

        <div id="tab_voli" class="col s12">
            <%= render 'layouts/flights' %>
            <br/>
        </div>

        <div id="tab_hotel" class="col s12">
            <%= render 'layouts/hotels' %>
            <br/>
        </div>

        <% if current_user.has_role? :company_user or current_user.has_role? :admin %>
        <div id="tab_auto" class="col s12">
            <%= render 'layouts/cars' %>
            <br/>
        </div>
        <% end %>

    </div>

<% else %>
    <%= render 'layouts/flights' %>
    <br/>
<% end %>

app/views/layouts/_cities.html.erb
<optgroup label="Italia">
  <option id="Alghero" value="27536503">Alghero</option>
  <option id="Ancona" value="27536583">Ancona</option>
  <option id="Bari" value="27539556">Bari</option>
  <option id="Bologna" value="27539470">Bologna</option>
  <option id="Cagliari" value="27539679">Cagliari</option>
  <option id="Catania" value="27540562">Catania</option>
  <option id="Firenze" value="27541640">Firenze</option>
  <option id="Genova" value="27541884">Genova</option>
  <option id="Lamezia" value="27546311">Lamezia Terme</option>
  <option id="Milano" value="27544068">Milano</option>
  <option id="Napoli" value="27545086">Napoli</option>
  <option id="Olbia" value="27545213">Olbia</option>
  <option id="Palermo" value="27545989">Palermo</option>
  <option id="Parma" value="27545986">Parma</option>
  <option id="Perugia" value="27545929">Perugia</option>
  <option id="Pescara" value="27546050">Pescara</option>
  <option id="Pisa" value="27546040">Pisa</option>
  <option id="Reggio_Calabria" value="27546148">Reggio Calabria</option>
  <option id="Rimini" value="27546187">Rimini</option>
  <option id="Roma" value="27539793">Roma</option>
  <option id="Torino" value="27547248">Torino</option>
  <option id="Trieste" value="27547250">Trieste</option>
  <option id="Venezia" value="27547373">Venezia</option>
  <option id="Verona" value="27547432">Verona</option>
</optgroup>
<!-- Europa -->
<optgroup label="Europa">
  <option id="Atene" value="27548174">Atene</option>
  <option id="Amsterdam" value="27536561">Amsterdam</option>
  <option id="Barcellona" value="27548283">Barcellona</option>
  <option id="Berlino" value="27547053">Berlino</option>
  <option id="Copenaghen" value="27539902">Copenaghen</option>
  <option id="Dublino" value="27540823">Dublino</option>
  <option id="Ginevra" value="33735985">Ginevra</option>
  <option id="Helsinki" value="27542027">Helsinki</option>
  <option id="Istanbul" value="27542903">Instabul</option>
  <option id="Lisbona" value="27544072">Lisbona</option>
  <option id="Londra" value="27544008">Londra</option>
  <option id="Madrid" value="27544850">Madrid</option>
  <option id="Monaco_di_Baviera" value="27545034">Monaco di Baviera</option>
  <option id="Mosca" value="27539438">Mosca</option>
  <option id="Oslo" value="27538634">Oslo</option>
  <option id="Parigi" value="27539733">Parigi</option>
  <option id="Praga" value="27546033">Praga</option>
  <option id="Stoccolma" value="27539477">Stoccolma</option>
  <option id="Varsavia" value="27547454">Varsavia</option>
  <option id="Vienna" value="27547395">Vienna</option>
</optgroup>

app/views/layouts/_flights.html.erb
    
    <div class="padding-div">

        <div class="left" style="width: 60%;">
             <div style="float: left; width: 50%; padding-right: 20px;">
                <label>Città di partenza</label>
                <select id="cittaPartenza">
                    <option value="none" disabled selected>Seleziona la città di partenza</option>
                    <%= render 'layouts/airports' %>
                </select>
            </div>
        
            <div style="float: left; width: 50%; padding-right: 20px;">
                <label>Città di arrivo</label>
                <select id="cittaArrivo">
                    <option value="none" disabled selected>Seleziona la città di arrivo</option>
                   <%= render 'layouts/airports' %>
                </select>
            </div>

            <div style="clear:both; height: 70px;"></div>

            <div style="float: left; width: 50%; padding-right: 20px;">
                <label style="padding-bottom: 14px;"> Andata: </label>
                <input type="text" id="dataAndata" class="datepicker"><br/><br/>
            </div>

            <div style="float: left; width: 50%; padding-right: 20px;">
                <label style="padding-bottom: 0px;">
                    <input type="checkbox" class="filled-in" id="voli_check" OnClick="abilitaRitorno(this);" style="padding-bottom: 32px;"/>
                    <span id="a" style="padding-bottom: 32px;">Ritorno:</span>
                </label>
                <input type="text" id="dataRitorno" disabled="true" class="datepicker"><br/><br/>
            </div>

            <div style="clear:both; height: 40px;"></div>
        
            <div style="float: left; width: 50%; padding-right: 20px;">
                <label>Passeggeri:</label>
                <a id="a-" class="btn-floating btn-small waves-effect black"><i class="material-icons">remove</i></a>
                <label id="passeggeri">1</label>
                <a id="aadd" class="btn-floating btn-small waves-effect black"><i class="material-icons">add</i></a>
            </div>

             <% if current_user %>
               <div style="float: left; width: 50%; padding-right: 20px;">
                   <label>Meteo:</label>
                   <div id="meteo">
                        <label class="weather">Città:</label>
                        <label id="nomeCittaArrivo" class="weather"></label>
                         <div style="clear:both;"></div>
                         <label class="weather">Temperatura:</label>
                        <label id="meteoCittaArrivo" class="weather"></label>
                         <div style="clear:both;"></div>
                         <label class="weather">Descrizione:</label>
                        <label id="descrizioneCittaArrivo" class="weather"></label>
                    </div>
            
                </div>
            <% end %>
        </div>
         <% if current_user %>
            <div class="left" style="width: 40%;">
                <label>Informazioni Aeroporti:</label><br/>
                <div id="info" style="padding-left: 10px;">
                    <label style="font-size: 16pt;">Aeroporto di partenza:</label>
                    <label id="infoPartenza" style="font-size: 12pt"></label>
                    <div style="clear:both;"></div>
                    <label style="font-size: 16pt;">Aeroporto di arrivo:</label>
                    <label style="font-size: 12pt" id="infoArrivo"></label>
                    <div style="clear:both;"></div></div>
            </div>
        <% end %>

        <div style="clear:both;"></div>

        <% if current_user %>
            <div>
                <label>Tracker voli:</label><br/>
                <label style="font-size: 16pt;" id="tratta"></label>
                <label style="font-size: 12pt" id="voliDisponibili"></label>
                <%= link_to "Verifica voli", "javascript:void(0)", id: "infovoli", style: "size: 20;", class: "btn waves-effect waves-light hoverable" %>
            </div>
        <% end %>

    </div>
    
    <div style="clear:both;"></div>
    <br/>

app/views/layouts/_footer.html.erb
<div class="push-footer"></div>
<div id="footer" class="page-footer">
    © 2018 Copyright Text
    <%= link_to 'Contatti', contatti_contatti_path %>
    <% if !current_user %>
        <%= link_to 'Statistiche', statistics_path %>
    <% end %>
</div>

app/views/layouts/_hotels.html.erb
    <div class="padding-div">
        <div style="float: left; width: 30%; padding-right: 20px;">
            <label>Città:</label>
            <select id="cittaHotel">
                <option value="none" disabled selected>Seleziona la città</option>
                <%= render 'layouts/cities' %>
            </select>
        </div>

        <div style="clear:both; height: 70px;"></div>

        <div style="float: left; width: 15%; padding-right: 20px;">
            <label>Check in:</label>
            <input type="text" id="dataCheckin" class="datepicker"><br/><br/>
        </div>

        <div style="float: left; width: 15%; padding-right: 20px;">
            <label>Check out: </label>
            <input type="text" id="dataCheckout" class="datepicker"><br/><br/>
        </div>

        <div style="clear:both; height: 70px;"></div>

        <div style="float: left; width: 15%; padding-right: 20px;">
            <label>Numero persone:</label>
            <select id="numeroPersoneHotel">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
            </select>
        </div>

        <div style="float: left; width: 15%; padding-right: 20px;">
            <label>Numero stanze:</label>
            <select id="numeroStanze">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
            </select>
        </div>
        
    </div>

    <div style="clear:both;"></div>
    <br/>

app/views/layouts/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Profilo', edit_user_registration_path %></li>
  <li><%= link_to 'Statistiche', statistics_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Esci', destroy_user_session_path, method: :delete %></li>
</ul>


<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <%= link_to image_tag("logo.jpg", class:"logo", :alt => "LOGO"), root_path %>

            <% if current_user %>
            <ul id="nav-mobile" class="right hide-on-med-and-down navbar-buttons">
                <li class="valign-wrapper" id="vb">                        
                    <a class="btn dropdown-trigger hoverable chip" data-target="dropdown1">
                        <%= image_tag(current_user.avatar.url(:thumb), class:"user_avatar left") %>
                        <%= current_user.first_name %>
                    </a>
                </li>
            </ul>

            <% else %>
            <ul id="nav-mobile" class="right hide-on-med-and-down navbar-buttons">
                <li id="vb"><%= link_to 'Accedi', new_user_session_path, class: 'waves-effect waves-light btn hoverable' %></li>
                <li id="vb"><%= link_to 'Registrati', new_user_registration_path, class: 'waves-effect waves-light btn hoverable' %></li>
            </ul>
            <% end %>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyTravel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "logo.png" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= javascript_tag do%>
	    <% if current_user%>
        window.user_email = "<%=j current_user.email %>"
	    <% else %>
        window.user_email = "guest"
	    <% end %>
    <% end %>
    <div id="container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
      <%= yield %>
      <br/>
      
    </div>

    <%= render 'layouts/footer' %>

  </body>

</html>